# Generated by Django 5.1 on 2024-08-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dadoscoletados',
            old_name='quantidade_moradores',
            new_name='qtd_moradores',
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True),
        ),
    ]
