# Generated by Django 5.1 on 2024-08-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0002_rename_quantidade_moradores_dadoscoletados_qtd_moradores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscoletados',
            name='endereco',
            field=models.CharField(default='Endereço', max_length=255),
            preserve_default=False,
        ),
    ]
