# Generated by Django 5.1 on 2024-08-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0003_dadoscoletados_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscoletados',
            name='imovel_inspecionado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='imovel_recuperado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='imovel_tratado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='numero_amostra_final',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='numero_amostra_inicial',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='numero_quarteirao',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_amostras',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_a1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_a2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_b',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_c',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_d1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_e',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='quantidade_depositos_tratatados',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='quantidade_larvicida',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dadoscoletados',
            name='visita_normal',
            field=models.BooleanField(default=False),
        ),
    ]
