# Generated by Django 5.1 on 2024-08-29 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0004_dadoscoletados_imovel_inspecionado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscoletados',
            name='qtd_deposito_d2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
