# Generated by Django 5.1 on 2024-08-29 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0005_dadoscoletados_qtd_deposito_d2'),
    ]

    operations = [
        migrations.AddField(
            model_name='dadoscoletados',
            name='tipo_imovel',
            field=models.CharField(choices=[('R', 'Residencial'), ('C', 'Comercial'), ('TB', 'Terreno Baldio'), ('PE', 'Ponto Estratégico'), ('O', 'Outros')], default='R', max_length=2),
        ),
    ]
