# Generated by Django 5.1 on 2024-08-30 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleta_dados', '0006_dadoscoletados_tipo_imovel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoscoletados',
            name='numero_amostra_final',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='numero_amostra_inicial',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_amostras',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_a1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_a2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_b',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_c',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_d1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_d2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_deposito_e',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='qtd_moradores',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='quantidade_depositos_tratatados',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='dadoscoletados',
            name='quantidade_larvicida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
